[package]
name = "nes-rs"
version = "0.1.2"
authors = ["Drew Chandler <andrewschandler@gmail.com>"]

[[bin]]
name = "nes-rs"
path = "src/main.rs"
required-features = ["gui"]

[features]
default = ["gui"]
gui = ["minifb"]

[dependencies]
minifb = { version = "0.9.0", optional = true }
